/**
 * Regenerated by `yarn hardhat:deploy` from the deployment records under packages/hardhat/deployments/.
 * Empty until the first deploy; edits are overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-hbar/contract";

const deployedContracts = {} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
