name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run core lint
        run: yarn core:lint --max-warnings=0

      - name: Check typings on core
        run: yarn core:check-types

      - name: Run core tests
        run: yarn core:test

      - name: Run nextjs lint
        run: yarn next:lint --max-warnings=0

      - name: Check typings on nextjs
        run: yarn next:check-types

      - name: Run nextjs tests
        run: yarn next:test

      - name: Build nextjs
        run: yarn next:build

      - name: Run hardhat lint
        run: yarn hardhat:lint --max-warnings=0

      - name: Compile contracts
        run: yarn hardhat:compile

      - name: Check typings on hardhat
        run: yarn hardhat:check-types

      - name: Run contract tests
        run: yarn hardhat:test
